### ISSUE TITLE
React用ディレクトリの初期化

### ISSUE THREAD

**Issue by d-kimuson** [kaito1002/Zwitter#1]
## To do

- Zwitter直下にfrontendディレクトリ(React)の設置
- React側でbuild時に以下にコピーを設置
  1. Zwitter/nginx/dist/static
  2. Zwitter/django_project/dist/index.html
  3. Zwitter/django_project/dist/static

お願いします＼(^o^)／

**Comment by Shigi-p** [comment]
指定の位置にディレクトリ設置完了
また上記の位置にコピーした
たぶんできた
