### ISSUE TITLE
APIのレスポンスの修正

### ISSUE THREAD

**Issue by Shigi-p** [kaito1002/Zwitter#31]
「/api/subjects/search/?keyword=」のAPIで検索をかけたときに、idとnameを持つオブジェクトのリストで返ってくる。
「/api/subjects/user_related_exists/」のAPIはidとname、また最新年度のlatestと年度情報のyearのリストで返ってくるので、「/api/subjects/search/?keyword=」のAPIで検索をかけたときもlatestとyearを返すようにしてほしい。
(yearが存在しなければundifinedで返してもらって構わない)

**Comment by d-kimuson** [comment]
数日待ってくれ

**Comment by d-kimuson** [comment]
指定の仕様を満たす api/subjects/search_user_related エンドポイントを追加したよ
kwskはapi docsみてね
