### ISSUE TITLE
posts投稿時のuserをログインユーザーから取るように変更

### ISSUE THREAD

**Issue by Shigi-p** [kaito1002/Zwitter#38]
zweet実装するときに気づいたんですけど、posts投稿時にcontents、commentsと同じく現在のログインユーザーから情報を取ってくるように変更よろしくお願いします.

**Comment by Shigi-p** [comment]
zweetに対してリプライを送れるのはtwetterリスペクトで大いに賛同できるけど、リプライに対してリプライするとか考えたときに実装が大変なので、リプライの階層は1階層だけにする予定です.

**Comment by d-kimuson** [comment]
変更終わりました.
