### ISSUE TITLE
画像アップロードのフロント側の処理について

### ISSUE THREAD

**Issue by d-kimuson** [kaito1002/Zwitter#45]
@Shigi-p 
ファイル名被りNGだったり, サイズ考えてなかったりでガバガバだけど一応バック側で仮の画像の受け取り実装できてるのでフロント側しくよろ

branch: feature/profile_image

こっちでaxiosから投げるサンプル用意してるから
- django_project/test_upload/upload.html
- localhost:8000/test_upload/
を参考にしてけろ！

**Comment by d-kimuson** [comment]
developに結合したのでそちらで対応お願いします

**Comment by Shigi-p** [comment]
確認したんで頑張って今日のうちにはしたいと思いまふ

**Comment by Shigi-p** [comment]
とりあえず投げられるようにはしました.
Zwitterの右メニューからconfig、アップロード画面に飛ぶのでアップロード.
うまくいくとZwitterに戻ってくると思うので、右サイドバーにアップした画像が出ていればOK.
