### ISSUE TITLE
postAPIの修正

### ISSUE THREAD

**Issue by Shigi-p** [kaito1002/Zwitter#55]
postmanでも実際にAPI叩いてみても、bef_postにint型で数字を渡しているのにもかかわらずnullになるので、このへん確認してみてくださいな.

**Comment by Shigi-p** [comment]
あとpostmanにて、実験としてpostしたコメントの数々をdeleteで消そうと思ったとき、parmission deniedでfalseになるものがあります.これってpostman側でのTOKENの設定っすよね.

**Comment by Shigi-p** [comment]
↑postmanでTOKENに自分のぶち込んだら自己解決しました.

**Comment by d-kimuson** [comment]
確認します！

**Comment by d-kimuson** [comment]
三項演算子逆にしてました！お恥ずかしい！治りました！
確認よろすく☆

**Comment by Shigi-p** [comment]
今更ですが確認できました！！！リプできる！！
