### ISSUE TITLE
Actionsでinstall dependenciesにてエラー

### ISSUE THREAD

**Issue by Shigi-p** [kaito1002/Zwitter#60]
よくわからないのが正直()
対応お願いしたいっす
エラーコード詳細
`
  python3-zope.interface uidmap xdelta3
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  libpython3.7 libpython3.7-dev libpython3.7-minimal libpython3.7-stdlib
  python3.7 python3.7-minimal
Suggested packages:
  python3.7-venv python3.7-doc
The following NEW packages will be installed:
  libmysqlclient-dev libpython3.7 libpython3.7-dev libpython3.7-minimal
  libpython3.7-stdlib python3.7 python3.7-dev python3.7-minimal
0 upgraded, 8 newly installed, 0 to remove and 19 not upgraded.
Need to get 55.8 MB of archives.
After this operation, 119 MB of additional disk space will be used.
Get:1 http://azure.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 libpython3.7-minimal amd64 3.7.3-2~18.04.1 [545 kB]
Get:2 http://azure.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 python3.7-minimal amd64 3.7.3-2~18.04.1 [1701 kB]
Ign:3 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libmysqlclient-dev amd64 5.7.27-0ubuntu0.18.04.1
Get:4 http://azure.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 libpython3.7-stdlib amd64 3.7.3-2~18.04.1 [1736 kB]
Get:5 http://azure.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 libpython3.7 amd64 3.7.3-2~18.04.1 [1499 kB]
Err:3 http://security.ubuntu.com/ubuntu bionic-updates/main amd64 libmysqlclient-dev amd64 5.7.27-0ubuntu0.18.04.1
  404  Not Found [IP: 52.177.174.250 80]
Get:6 http://azure.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 libpython3.7-dev amd64 3.7.3-2~18.04.1 [48.4 MB]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/m/mysql-5.7/libmysqlclient-dev_5.7.27-0ubuntu0.18.04.1_amd64.deb  404  Not Found [IP: 52.177.174.250 80]
Get:7 http://azure.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 python3.7 amd64 3.7.3-2~18.04.1 [284 kB]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Get:8 http://azure.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 python3.7-dev amd64 3.7.3-2~18.04.1 [511 kB]
Fetched 54.7 MB in 3s (21.2 MB/s)
##[error]Process completed with exit code 100.
`

**Comment by Shigi-p** [comment]
![Screenshot from 2019-11-23 12-15-32](https://user-images.githubusercontent.com/38338116/69472298-95355f00-0deb-11ea-97fb-23c23091c155.png)

**Comment by d-kimuson** [comment]
ろーかるでもおきる?

**Comment by Shigi-p** [comment]
いや、ローカルだと何の問題もなく動かせてるっぽい

**Comment by d-kimuson** [comment]
直しましたっす
